"""Kalshi adapter metadata. See docs/adr/0001-adapter-registry.md."""
from __future__ import annotations

from edge_catcher.adapters.base import AdapterMeta
from edge_catcher.fees import STANDARD_FEE, INDEX_FEE


KALSHI_ADAPTERS: list[AdapterMeta] = [
	AdapterMeta(
		id="kalshi",
		exchange="kalshi",
		name="Kalshi BTC",
		description="Download settled BTC contracts (KXBTC/D/W/M/15M) and trade history from Kalshi.",
		db_file="data/kalshi.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-03-21",
		markets_yaml="config/markets.yaml",
	),
	AdapterMeta(
		id="kalshi_sports",
		exchange="kalshi",
		name="Kalshi Sports",
		description="Download settled NBA/MLB spread and moneyline contracts from Kalshi.",
		db_file="data/kalshi-sports.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-sports.yaml",
	),
	AdapterMeta(
		id="kalshi_crypto",
		exchange="kalshi",
		name="Kalshi Crypto (Altcoins)",
		description="Download settled altcoin contracts (ETH/SOL/XRP/DOGE/BNB/HYPE — hourly, daily, 15M) from Kalshi.",
		db_file="data/kalshi-altcrypto.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-altcrypto.yaml",
	),
	AdapterMeta(
		id="kalshi_weather",
		exchange="kalshi",
		name="Kalshi Weather",
		description="Download settled weather contracts (temperature, rain) from Kalshi.",
		db_file="data/kalshi-weather.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-weather.yaml",
	),
	AdapterMeta(
		id="kalshi_financials",
		exchange="kalshi",
		name="Kalshi Financials",
		description="Download settled financials/economics contracts (Nasdaq, S&P, yields, jobless) from Kalshi.",
		db_file="data/kalshi-financials.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-financials.yaml",
		fee_overrides={"KXINX": INDEX_FEE, "KXNASDAQ100": INDEX_FEE},
	),
	AdapterMeta(
		id="kalshi_entertainment",
		exchange="kalshi",
		name="Kalshi Entertainment",
		description="Download settled entertainment contracts (Spotify charts, awards) from Kalshi.",
		db_file="data/kalshi-entertainment.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-entertainment.yaml",
	),
	AdapterMeta(
		id="kalshi_politics",
		exchange="kalshi",
		name="Kalshi Politics & Elections",
		description="Download settled politics/election/mentions contracts from Kalshi.",
		db_file="data/kalshi-politics.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-politics.yaml",
	),
	AdapterMeta(
		id="kalshi_esports",
		exchange="kalshi",
		name="Kalshi Esports",
		description="Download settled esports contracts (CS2, LoL, ATP tennis, J-League) from Kalshi.",
		db_file="data/kalshi-esports.db",
		fee_model=STANDARD_FEE,
		requires_api_key=False,
		api_key_env_var="KALSHI_API_KEY",
		default_start_date="2025-01-01",
		markets_yaml="config/markets-esports.yaml",
	),
]
